url: https://ralphjohncortez.github.io
baseurl:

# Site settings
title: Ralph John Cortez
email: ralph.john.cortez@gmail.com
description: "IT Support & Helpdesk | Exploring Cybersecurity & Networks | Portfolio"


# Team names, titles and social links
people:
- name: Ralph John Cortez
  pic: profile
  position: IT Support & Helpdesk Technician II
  social:
    - title: twitter
      url: # https://x.com/ralphcortezzz
    - title: facebook
      url: # https://www.facebook.com/ralphcortezzz
    - title: google-plus
      url: # ralph.john.cortez@gmail.com
    - title: file-pdf-o
      url: resume.pdf

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/ralphcortezzz
  - title: facebook
    url: https://www.facebook.com/ralphcortezzz
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url:
  - title: github
    url: https://github.com/ralphjohncortez

# Postal address (add as many lines as necessary)
address:
  - line: BLK 49 LOT 71 Cristo Rey
  - line: Capas, Tarlac

# Build settings
markdown: kramdown
permalink: pretty
